name: Release

on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*.*.*"

jobs:
  programs:
    runs-on: ubuntu-latest
    name: Build and publish the SDK
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: "https://registry.npmjs.org"
      - uses: actions/cache@v2
        with:
          path: ./.yarn
          key: ${{ runner.os }}-modules-${{ hashFiles('./.yarn/**/*.js') }}
      - run: yarn install
      - run: yarn build
      - name: Publish
        run: |
          echo 'npmAuthToken: "${NODE_AUTH_TOKEN}"' >> .yarnrc.yml
          git update-index --assume-unchanged .yarnrc.yml
          yarn lerna publish --yes from-package --no-verify-access
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
